/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.educacionit;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Curso JPA - Hibernate");
        Runnable r = new EjemploQueryClientSide();
        r.run();
    }
}
